# This is the start of the deployment manifest
# They are looking for  Kubernetes deployment, Kubernetes service, Secret configs and DB config via env variables
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-deployment
spec:
  template:
    spec:
      env:
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-clusterip
spec:
---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secret
spec:
